let sun = document.getElementById('sun');
let mercury = document.getElementById('mercury');
let mercuryInfo = document.getElementById('mercuryInfo');
let venus = document.getElementById('venus');
let venusInfo = document.getElementById('venusInfo');
let earth = document.getElementById('earth');
let earthInfo = document.getElementById('earthInfo');
let mars = document.getElementById('mars');
let marsInfo = document.getElementById('marsInfo');
let jupiter = document.getElementById('jupiter');
let jupiterInfo = document.getElementById('jupiterInfo');
let saturn = document.getElementById('saturn');
let saturnInfo = document.getElementById('saturnInfo');
let uranus = document.getElementById('uranus');
let uranusInfo = document.getElementById('uranusInfo');
let neptune = document.getElementById('neptune');
let neptuneInfo = document.getElementById('neptuneInfo');
let pluto = document.getElementById('pluto');
let plutoInfo = document.getElementById('plutoInfo');
let objects = new tracking.ObjectTracker('face');

objects.on('track', function(event) {
  if (event.data.length === 0) {
    // No objects were detected in this frame.
  } else {
    event.data.forEach(function(rect) {
      // console.log(rect.x, rect.y, rect.height, rect.width)
      console.log(rect.height);
      if (rect.height >= 120){
        // mercury
        sun.style.width = "360px";
        sun.style.top = "0px";
        mercury.style.width = "200px";
        mercury.style.top = "360px";
        mercury.style.left = "50px";
        mercuryInfo.style.visibility = "visible";
        venus.style.width = "150px"
        venus.style.top = "2125px";
        venus.style.left = "23px";
        venusInfo.style.visibility = "hidden";
        earth.style.width = "100px";
        earth.style.top = "2275px";
        earth.style.left = "76px";
        earthInfo.style.visibility = "hidden";
        mars.style.width = "75px";
        mars.style.top = "2375px";
        mars.style.left = "90px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.width = "50px";
        jupiter.style.top = "2450px";
        jupiter.style.left = "150px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.width = "40px"
        saturn.style.top = "2500px";
        saturn.style.left = "200px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.width = "30px";
        uranus.style.top = "2540px";
        uranus.style.left = "250px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.width = "20px";
        neptune.style.top = "2570px";
        neptune.style.left = "275px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.width = "10px";
        pluto.style.top = "2590px";
        pluto.style.left = "330px";
        plutoInfo.style.visibility = "hidden";
      }
      else if (rect.height >= 100 && rect.height < 120){
        // venus
        sun.style.top = "-20px";
        mercury.style.width = "150px";
        mercury.style.top = "340px";
        mercury.style.left = "50px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "200px";
        venus.style.top = "490px";
        venus.style.left = "50px";
        venusInfo.style.visibility = "visible";
        earth.style.width = "150px";
        earth.style.top = "2135px";
        earth.style.left = "76px";
        earthInfo.style.visibility = "hidden";
        mars.style.width = "100px";
        mars.style.top = "2285px";
        mars.style.left = "90px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.width = "75px";
        jupiter.style.top = "2385px";
        jupiter.style.left = "150px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.width = "50px";
        saturn.style.top = "2460px";
        saturn.style.left = "200px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.width = "40px";
        uranus.style.top = "2510px";
        uranus.style.left = "250px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.top = "30px";
        neptune.style.top = "2550px";
        neptune.style.left = "275px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.width = "20px";
        pluto.style.top = "2580px";
        pluto.style.left = "330px";
        plutoInfo.style.visibility = "hidden";

      }
      else if (rect.height >= 80 && rect.height < 100){
        // earth
        sun.style.top = "-40px";
        mercury.style.width = "100px";
        mercury.style.top = "320px";
        mercury.style.left = "50px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "150px";
        venus.style.top = "420px";
        venus.style.left = "50px";
        venusInfo.style.visibility = "hidden";
        earth.style.width = "200px";
        earth.style.top = "570px";
        earth.style.left = "50px";
        earthInfo.style.visibility = "visible";
        mars.style.width = "150px";
        mars.style.top = "2155px";
        mars.style.left = "90px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.width = "100px";
        jupiter.style.top = "2305px";
        jupiter.style.left = "150px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.width = "75px";
        saturn.style.top = "2405px";
        saturn.style.left = "200px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.width = "50px";
        uranus.style.top = "2480px";
        uranus.style.left = "250px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.width = "40px";
        neptune.style.top = "2530px";
        neptune.style.left = "275px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.width = "30px";
        pluto.style.top = "2570px";
        pluto.style.left = "330px";
        plutoInfo.style.visibility = "hidden";
      }
      else if (rect.height >= 70 && rect.height < 80){
        // mars
        sun.style.top = "-60px";
        mercury.style.width = "75px";
        mercury.style.top = "300px";
        mercury.style.left = "50px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "100px";
        venus.style.top = "375px";
        venus.style.left = "50px";
        venusInfo.style.visibility = "hidden";
        earth.style.width = "150px";
        earth.style.top = "475px";
        earth.style.left = "50px";
        earthInfo.style.visibility = "hidden";
        mars.style.width = "200px";
        mars.style.top = "625px";
        mars.style.left = "50px";
        marsInfo.style.visibility = "visible";
        jupiter.style.width = "150px";
        jupiter.style.top = "2185px";
        jupiter.style.left = "150px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.width = "100px";
        saturn.style.top = "2335px";
        saturn.style.left = "200px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.width = "75px";
        uranus.style.top = "2435px";
        uranus.style.left = "250px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.width = "50px";
        neptune.style.top = "2510px";
        neptune.style.left = "275px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.width = "40px";
        pluto.style.top = "2560px";
        pluto.style.left = "330px";
        plutoInfo.style.visibility = "hidden";
      }
      else if (rect.height >= 60 && rect.height < 70){
        // jupiter
        sun.style.top = "-80px";
        mercury.style.width = "50px";
        mercury.style.top = "280px";
        mercury.style.left = "50px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "75px";
        venus.style.top = "355px";
        venus.style.left = "50px";
        venusInfo.style.visibility = "hidden";
        earth.style.width = "100px";
        earth.style.top = "430px";
        earth.style.left = "50px";
        earthInfo.style.visibility = "hidden";
        mars.style.width = "150px";
        mars.style.top = "530px";
        mars.style.left = "50px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.width = "200px";
        jupiter.style.top = "680px";
        jupiter.style.left = "50px";
        jupiterInfo.style.visibility = "visible";
        saturn.style.width = "150px";
        saturn.style.top = "2225px";
        saturn.style.left = "200px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.width = "100px";
        uranus.style.top = "2375px";
        uranus.style.left = "250px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.width = "75px";
        neptune.style.top = "2475px";
        neptune.style.left = "275px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.width = "50px";
        pluto.style.top = "2550px";
        pluto.style.left = "330px";
        plutoInfo.style.visibility = "hidden";
      }
      else if (rect.height >= 50 && rect.height < 60){
        // saturn
        sun.style.top = "-100px";
        mercury.style.width = "40px";
        mercury.style.top = "260px";
        mercury.style.left = "50px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "50px";
        venus.style.top = "300px";
        venus.style.left = "50px";
        venusInfo.style.visibility = "hidden";
        earth.style.width = "75px";
        earth.style.top = "350px";
        earth.style.left = "50px";
        earthInfo.style.visibility = "hidden";
        mars.style.width = "100px";
        mars.style.top = "425px";
        mars.style.left = "50px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.width = "150px";
        jupiter.style.top = "525px";
        jupiter.style.left = "50px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.width = "200px";
        saturn.style.top = "675px";
        saturn.style.left = "50px";
        saturnInfo.style.visibility = "visible";
        uranus.style.width = "150px";
        uranus.style.top = "2275px";
        uranus.style.left = "250px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.width = "100px";
        neptune.style.top = "2425px";
        neptune.style.left = "275px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.width = "75px";
        pluto.style.top = "2525px";
        pluto.style.left = "330px";
        plutoInfo.style.visibility = "hidden";
      }
      else if (rect.height >= 40 && rect.height < 50){
        // uranus
        sun.style.top = "-120px";
        mercury.style.width = "30px";
        mercury.style.top = "240px";
        mercury.style.left = "50px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "40px";
        venus.style.top = "270px";
        venus.style.left = "50px";
        venusInfo.style.visibility = "hidden";
        earth.style.width = "50px";
        earth.style.top = "310px";
        earth.style.left = "50px";
        earthInfo.style.visibility = "hidden";
        mars.style.width = "75px";
        mars.style.top = "360px";
        mars.style.left = "50px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.width = "100px";
        jupiter.style.top = "435px";
        jupiter.style.left = "50px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.width = "150px";
        saturn.style.top = "535px";
        saturn.style.left = "50px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.width = "200px";
        uranus.style.top = "685px";
        uranus.style.left = "50px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.width = "150px";
        neptune.style.top = "2350px";
        neptune.style.left = "275px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.width = "100px";
        pluto.style.top = "2500px";
        pluto.style.left = "330px";
        plutoInfo.style.visibility = "hidden";
      }
      else if (rect.height >= 35 && rect.height < 40){
        // neptune
        sun.style.top = "-140px";
        mercury.style.width = "20px";
        mercury.style.top = "220px";
        mercury.style.left = "50px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "30px";
        venus.style.top = "240px";
        venus.style.left = "50px";
        venusInfo.style.visibility = "hidden";
        earth.style.width = "40px"
        earth.style.top = "270px";
        earth.style.left = "50px";
        earthInfo.style.visibility = "hidden";
        mars.style.width = "50px";
        mars.style.top = "310px";
        mars.style.left = "50px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.width = "75px";
        jupiter.style.top = "360px";
        jupiter.style.left = "50px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.width = "100px";
        saturn.style.top = "440px";
        saturn.style.left = "50px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.width = "150px";
        uranus.style.top = "540px";
        uranus.style.left = "50px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.width = "200px";
        neptune.style.top = "690px";
        neptune.style.left = "50px";
        neptuneInfo.style.visibility = "visible";
        pluto.style.width = "150px";
        pluto.style.top = "2450px";
        pluto.style.left = "330px";
        plutoInfo.style.visibility = "hidden";
      }
      else if (rect.height < 35){
        // pluto
        sun.style.top = "-160px";
        mercury.style.width = "10px";
        mercury.style.top = "200px";
        mercury.style.left = "50px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "20px";
        venus.style.top = "210px";
        venus.style.left = "50px";
        venusInfo.style.visibility = "hidden";
        earth.style.width = "30px";
        earth.style.top = "230px";
        earth.style.left = "50px";
        earthInfo.style.visibility = "hidden";
        mars.style.width = "40px";
        mars.style.top = "260px";
        mars.style.left = "50px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.width = "50px";
        jupiter.style.top = "300px";
        jupiter.style.left = "50px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.width = "75px";
        saturn.style.top = "350px";
        saturn.style.left = "50px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.width = "100px";
        uranus.style.top = "425px";
        uranus.style.left = "50px";
        uranusInfo.style.visibility = "visible";
        neptune.style.width = "150px";
        neptune.style.top = "525px";
        neptune.style.left = "50px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.width = "200px";
        pluto.style.top = "675px";
        pluto.style.left = "50px";
        plutoInfo.style.visibility = "visible";
      }
      else {
        sun.style.top = "0px";
        mercury.style.width = "23px";
        mercury.style.top = "1838px";
        mercury.style.left = "0px";
        mercuryInfo.style.visibility = "hidden";
        venus.style.width = "53px";
        venus.style.top = "1861px";
        venus.style.left = "23px";
        venusInfo.style.visibility = "hidden";
        earth.style.width = "60px";
        earth.style.top = "1914px";
        earth.style.left = "76px";
        earthInfo.style.visibility = "hidden";
        mars.style.width = "53px";
        mars.style.top = "1974px";
        earth.style.left = "120px";
        marsInfo.style.visibility = "hidden";
        jupiter.style.width = "200px";
        jupiter.style.top = "2027px";
        jupiterInfo.style.visibility = "hidden";
        saturn.style.width = "150px";
        saturn.style.top = "2227px";
        saturnInfo.style.visibility = "hidden";
        uranus.style.width = "100px";
        uranus.style.top = "2377px";
        uranusInfo.style.visibility = "hidden";
        neptune.style.width = "100px";
        neptune.style.top = "2477px";
        neptuneInfo.style.visibility = "hidden";
        pluto.style.width = "23px";
        pluto.style.top = "2577px";
        plutoInfo.style.visibility = "hidden";
      }
    });
  }
});

tracking.track('#myVideo', objects, {camera: true})
